# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://a-dungeon-game.netlify.app/
title:   a dungeon game

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    parser:
      attribute:
        block: true
        title: true

params:
  description: >-
    A Dungeon Game is a lean tabletop fantasy dungeon crawler that's legally distinct from that
    other Dungeon game.
  images:
    - site-feature-image.png
